/**
 * Theme definitions for the 3 themes:
 *   - cupertino  (Apple light)
 *   - fluent     (Microsoft dark)
 *   - vercel     (Geek black)
 */

export const themes = {
  cupertino: {
    id: 'cupertino',
    name: 'Cupertino Light',
    monacoTheme: 'vs',
    bg: 'bg-[#f2f2f7]',
    headerBg: 'bg-white/80 backdrop-blur-xl border-b border-gray-200/60',
    headerText: 'text-gray-900',
    panelBg: 'bg-white/70 backdrop-blur-xl border border-gray-200/50',
    sidebarBg: 'bg-[#f9f9fb]/80 backdrop-blur-xl border border-gray-200/50',
    text: 'text-gray-800',
    subText: 'text-gray-500',
    accent: 'bg-blue-500',
    accentText: 'text-blue-600',
    btnBase: 'bg-white/90 border border-gray-200 text-gray-700 hover:bg-gray-50',
    btnActive: 'bg-blue-500 text-white border-transparent',
    btnDisabled: 'bg-gray-100/60 border border-gray-200/40 text-gray-300 cursor-not-allowed',
    runBtn: 'bg-red-500 hover:bg-red-600 text-white shadow-red-200 shadow-md',
    runBtnActive: 'bg-green-500 hover:bg-green-600 text-white shadow-green-200 shadow-md',
    divider: 'bg-gray-200/80',
    tag: 'bg-blue-100 text-blue-700',
    jsonKey: 'text-blue-700',
    jsonStr: 'text-green-700',
    jsonNum: 'text-orange-600',
    jsonBool: 'text-purple-600',
    jsonNull: 'text-gray-400',
    watchBg: 'bg-white/60 backdrop-blur-xl border border-gray-200/50',
    scrollbar: 'scrollbar-thumb-gray-300',
  },
  fluent: {
    id: 'fluent',
    name: 'Fluent Dark',
    monacoTheme: 'vs-dark',
    bg: 'bg-[#1a1a2e]',
    headerBg: 'bg-[#16213e]/90 backdrop-blur-xl border-b border-white/10',
    headerText: 'text-white',
    panelBg: 'bg-[#0f3460]/40 backdrop-blur-xl border border-white/10',
    sidebarBg: 'bg-[#16213e]/70 backdrop-blur-xl border border-white/10',
    text: 'text-gray-100',
    subText: 'text-gray-400',
    accent: 'bg-[#0078d4]',
    accentText: 'text-[#60cdff]',
    btnBase: 'bg-white/10 border border-white/15 text-gray-200 hover:bg-white/20',
    btnActive: 'bg-[#0078d4] text-white border-transparent',
    btnDisabled: 'bg-white/5 border border-white/5 text-gray-600 cursor-not-allowed',
    runBtn: 'bg-red-500/90 hover:bg-red-500 text-white shadow-red-900/40 shadow-lg',
    runBtnActive: 'bg-green-500/90 hover:bg-green-500 text-white shadow-green-900/40 shadow-lg',
    divider: 'bg-white/10',
    tag: 'bg-[#0078d4]/30 text-[#60cdff]',
    jsonKey: 'text-[#60cdff]',
    jsonStr: 'text-[#a8cc8c]',
    jsonNum: 'text-[#f8c555]',
    jsonBool: 'text-[#d2a8ff]',
    jsonNull: 'text-gray-500',
    watchBg: 'bg-[#0d1b2a]/70 backdrop-blur-xl border border-white/10',
    scrollbar: 'scrollbar-thumb-white/20',
  },
  vercel: {
    id: 'vercel',
    name: 'Vercel Black',
    monacoTheme: 'vs-dark',
    bg: 'bg-black',
    headerBg: 'bg-black/95 backdrop-blur-xl border-b border-white/10',
    headerText: 'text-white',
    panelBg: 'bg-[#111]/80 backdrop-blur-xl border border-white/10',
    sidebarBg: 'bg-[#0a0a0a]/90 backdrop-blur-xl border border-white/10',
    text: 'text-white',
    subText: 'text-gray-500',
    accent: 'bg-white',
    accentText: 'text-white',
    btnBase: 'bg-white/5 border border-white/15 text-white hover:bg-white/10',
    btnActive: 'bg-white text-black border-transparent',
    btnDisabled: 'bg-white/3 border border-white/5 text-gray-700 cursor-not-allowed',
    runBtn: 'bg-red-500 hover:bg-red-400 text-white shadow-red-500/30 shadow-lg',
    runBtnActive: 'bg-[#00e5a0] hover:bg-[#00ff99] text-black shadow-[#00e5a0]/30 shadow-lg',
    divider: 'bg-white/10',
    tag: 'bg-white/10 text-white',
    jsonKey: 'text-[#79c0ff]',
    jsonStr: 'text-[#a5d6ff]',
    jsonNum: 'text-[#f8c555]',
    jsonBool: 'text-[#ff7b72]',
    jsonNull: 'text-gray-600',
    watchBg: 'bg-[#0a0a0a]/90 backdrop-blur-xl border border-white/10',
    scrollbar: 'scrollbar-thumb-white/10',
  },
}
